# Generated by Django 4.2.3 on 2023-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='urgencia',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta',
            field=models.CharField(choices=[('trabajo', 'Trabajo'), ('hogar', 'Hogar'), ('estudio', 'Estudio')], default='trabajo', max_length=20),
        ),
    ]
